### ISSUE TITLE
Sevenbridges Files

### ISSUE THREAD

**Issue by shanshan1009** [cathalgking/single-cell-RNA-seq-analysis#1]
Thank you sososososo much for your tutorial about BD Rhapsody which is not popular. 
Actually, I am a beginner and I am wondering if there is any difference when I start R analysis from "RSEC_MolsPeCell" or "RSEC_ReadsPer Cell"  from SevenBridges. 
Also, is it necessary to use the huge file "RSEC_MolsPerCell_Unfiltered" or "RSEC_ReadsPerCell_Unfiltered" ?
I will be appreciated if I can get your help.

**Comment by cathalgking** [comment]
RSEC Mols per cell contains the count matrix you would use. You could look at the Unfiltered data if you suspect that your filtered data is missing cells for example or is not as expected.
